import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../scss/globals.scss";
import "./tailwind.css"
import Providers from "@/components/Providers";

const roboto = Roboto({ 
  subsets: ['latin'], 
  weight: ['100', '300', '400', '500', '700', '900'] 
});

export const metadata: Metadata = {
  title: "MADTEC-2025-M-478",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
